# Generated by Django 5.2.4 on 2026-04-02 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branch_item_cart_order_orderitem_payment_cartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventoryitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'InventoryItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventoryitemunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitname', models.TextField(db_column='unitName')),
                ('price', models.FloatField()),
                ('isdefault', models.BooleanField(db_column='isDefault')),
            ],
            options={
                'db_table': 'InventoryItemUnit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'ItemCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kompracdeliverytracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('statusat', models.DateTimeField(db_column='statusAt')),
                ('currentlat', models.FloatField(blank=True, db_column='currentLat', null=True)),
                ('currentlng', models.FloatField(blank=True, db_column='currentLng', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('actortype', models.TextField(db_column='actorType')),
                ('actorid', models.IntegerField(blank=True, db_column='actorId', null=True)),
            ],
            options={
                'db_table': 'KompraCDeliveryTracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kompracorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionnumber', models.TextField(db_column='transactionNumber', unique=True)),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.TextField()),
                ('scheduleddeliveryat', models.DateTimeField(blank=True, db_column='scheduledDeliveryAt', null=True)),
                ('estimateddeliveryat', models.DateTimeField(blank=True, db_column='estimatedDeliveryAt', null=True)),
                ('deliveredat', models.DateTimeField(blank=True, db_column='deliveredAt', null=True)),
                ('paymentmethod', models.TextField(db_column='paymentMethod')),
                ('paymentstatus', models.TextField(db_column='paymentStatus')),
                ('paymentreference', models.TextField(blank=True, db_column='paymentReference', null=True)),
                ('ridername', models.TextField(blank=True, db_column='riderName', null=True)),
                ('riderphone', models.TextField(blank=True, db_column='riderPhone', null=True)),
                ('customernote', models.TextField(blank=True, db_column='customerNote', null=True)),
                ('outletnote', models.TextField(blank=True, db_column='outletNote', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'KompraCOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kompracorderfee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('label', models.TextField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'KompraCOrderFee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kompracorderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricesnapshot', models.FloatField(db_column='priceSnapshot')),
                ('subtotal', models.FloatField()),
            ],
            options={
                'db_table': 'KompraCOrderItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('sortorder', models.IntegerField(db_column='sortOrder')),
            ],
            options={
                'db_table': 'Media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Outlet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outletdeliveryconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdeliveryactive', models.BooleanField(db_column='isDeliveryActive')),
                ('deliveryradiuskm', models.FloatField(db_column='deliveryRadiusKm')),
                ('basedeliveryfee', models.FloatField(db_column='baseDeliveryFee')),
                ('feeperkm', models.FloatField(db_column='feePerKm')),
                ('minorderamount', models.FloatField(blank=True, db_column='minOrderAmount', null=True)),
                ('maxorderamount', models.FloatField(blank=True, db_column='maxOrderAmount', null=True)),
                ('avgprepmins', models.IntegerField(db_column='avgPrepMins')),
            ],
            options={
                'db_table': 'OutletDeliveryConfig',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='api_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='api_cartitem',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
