# Generated by Django 5.2.4 on 2026-04-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_orderfee_orderitem_ordertracking_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventoryitem',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sku', models.TextField()),
                ('stock', models.IntegerField()),
                ('minstock', models.IntegerField(db_column='minStock')),
                ('category', models.TextField()),
                ('price', models.FloatField()),
                ('lowstock', models.BooleanField(db_column='lowStock')),
            ],
            options={
                'db_table': 'InventoryItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('isactive', models.BooleanField(db_column='isActive')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'ItemGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitname', models.TextField(db_column='unitName', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ItemUnit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kompracustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('passwordhash', models.TextField(db_column='passwordHash')),
                ('profilephoto', models.TextField(blank=True, db_column='profilePhoto', null=True)),
                ('isverified', models.BooleanField(db_column='isVerified')),
                ('isactive', models.BooleanField(db_column='isActive')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'KompraCustomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.TextField(blank=True, null=True)),
                ('rack', models.TextField(blank=True, null=True)),
                ('shelf', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'Organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orgitemcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('cost_of_sale', models.TextField(blank=True, null=True)),
                ('grouptype', models.TextField(blank=True, db_column='groupType', null=True)),
                ('sales', models.TextField(blank=True, null=True)),
                ('stocks', models.TextField(blank=True, null=True)),
                ('isactive', models.BooleanField(db_column='isActive')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'OrgItemCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymongoapikeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('secret_key', models.TextField()),
            ],
            options={
                'db_table': 'PaymongoAPIKeys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('isdefault', models.BooleanField(db_column='isDefault')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'DeliveryAddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'VatType',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
